# Generated by Django 5.1.4 on 2024-12-15 18:35

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a new tag (e.g. React, browser extension, etc.)', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='tag_name_case_insensitive_unique', violation_error_message='Tag already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(2)])),
                ('time_to_read', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tags', models.ManyToManyField(help_text='Select tags for this article', to='articles.tag')),
            ],
        ),
    ]
