# Generated by Django 5.1.4 on 2025-01-11 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_subscriberemail_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='short_desc',
            field=models.CharField(max_length=240, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(default='https://placehold.co/400x240', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
