# Generated by Django 5.1.4 on 2025-01-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_article_short_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.TextField(max_length=240, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='short description'),
        ),
    ]
