# Generated by Django 5.1.4 on 2025-02-14 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='table_of_content',
            field=models.TextField(default='- [Intro](#Intro)\n- [Examples](#Examples)\n    - [HTML](#HTML)\n    - [CSS](#CSS)\n    - [JavaScript](#JavaScript)\n    - [C#](#C#)\n    - [Bash](#Bash)\n- [Conclusion](#Conclusion)', validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
